# Generated by Django 5.2 on 2025-05-07 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('clinic', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='doctor_images/')),
                ('specialization', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=15)),
                ('whatsapp_number', models.CharField(max_length=15)),
                ('description', models.TextField()),
                ('output_video', models.FileField(blank=True, null=True, upload_to='doctor_videos/')),
            ],
        ),
    ]
