# Generated by Django 5.2 on 2025-05-08 02:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0003_doctorvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorvideo',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='doctorvideo',
            name='image',
            field=models.ImageField(upload_to='doctor_images/'),
        ),
    ]
